demo-web/Models/ErrorViewModel.cs
namespace demo_web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

demo-web/Models/LaiKep.cs
//Tạo class lãi suất LaiKep


namespace demo_web.Models

{
    public class LaiKep
    {

        //Tạo thuộc tính (attribute)
        public double TienGui { get; set; }
        public double LaiSuatGui { get; set; }
        public double KyHan { get; set; }
        public double SoLanDong { get; set; }
        
        public string TienLai { get; set; }
        public string TongTien { get; set; }

        //Tạo constructor
        public LaiKep() { }
        //Dùng tính chất overload để ghi đè lại hàm constructor
        //Biến bên class đặt tùy sở thích, cần minh bạch dễ hiểu
        public LaiKep(double gui, double laigui, double kyhan, double soLanDong)
        {
            this.TienGui = gui;
            this.LaiSuatGui = laigui;
            this.KyHan = kyhan;
            this.SoLanDong = soLanDong;
            this.TongTien = TinhTienLai(gui, laigui, kyhan, soLanDong).ToString("N0");
            this.TienLai = (double.Parse(this.TongTien) - gui).ToString("N0");


        }
        //Biến trong hàm đặt tùy sở thích, cần minh bạch dễ hiểu
        private double TinhTienLai(double gui, double laigui, double kyhan, double solandong)
        {
            var a = 1 + laigui / solandong / 100;
            var b = kyhan * solandong;
            var test = this.SoLanDong;
            return Math.Round(gui * Math.Pow(a, b), 0);



        }
        //Sau đó sang controller để gọi class

    }
}

demo-web/Models/LaiSuat.cs
//Tạo class lãi suất LaiSuat


namespace demo_web.Models

{
    public class LaiSuat
    {

        //Tạo thuộc tính (attribute)
        public int TienGui { get; set; }
        public int LaiSuatGui { get; set; }
        public int KyHan { get; set; }
        public double TienLai { get; set; }
        public double TongTien { get; set; }

        //Tạo constructor
        public LaiSuat() { }
        //Dùng tính chất overload để ghi đè lại hàm constructor
        //Biến bên class đặt tùy sở thích, cần minh bạch dễ hiểu
        public LaiSuat(int gui, int laigui, int kyhan)
        {
            this.TienGui = gui;
            this.LaiSuatGui = laigui;
            this.KyHan= kyhan;
            this.TienLai = TinhTienLai(gui, laigui, kyhan);
            this.TongTien = this.TienLai + gui;


        }
        //Biến trong hàm đặt tùy sở thích, cần minh bạch dễ hiểu
        private static double TinhTienLai(int a, int b, int c)
        {
            return (a * b / 100) * c / 12;
          


        }
        //Sau đó sang controller để gọi class

    }
}

demo-web/Models/SanPham.cs
namespace demo_web.Models
{
    public class SanPham
    {
        //Tạo biến
        public string TenSanPham { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
        public int TamTinh { get; set; }


        //Tạo hàm trống
        public SanPham() { }
        //Tạo hàm để tính toán
        public SanPham(string tenSanPham, int soLuong, int gia)
        {
            TenSanPham = tenSanPham;
            SoLuong = soLuong;
            DonGia = gia;
            TamTinh = soLuong * gia;
        }
    }
}

demo-web/Controllers/HomeController.cs
using demo_web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demo_web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

demo-web/Controllers/LaiKepController.cs
using demo_web.Models;
using Microsoft.AspNetCore.Mvc;

namespace demo_web.Controllers
{
    public class LaiKepController : Controller
    {
        public IActionResult Index()
        {
            //Gọi class rỗng
            LaiKep lk = new LaiKep();
            //Nhớ return về View
            return View(lk);
        }
        //Gọi class, nhớ HttpPost
        //Biến bên Controler phải lấy đúng name bên Index 

        [HttpPost]
        public IActionResult Index(double tiengui, double laisuatgui, double kyhan, double soLanDong)
        {
            LaiKep lk = new LaiKep(tiengui, laisuatgui, kyhan, soLanDong);
            return View(lk);
        }
        //{
        //    ViewData["SoNguyenA"] = songuyen1;
        //    ViewData["SoNguyenB"] = songuyen2;
        //    ViewData["SoNguyenC"] = songuyen3;
        //    double ketqua = (songuyen1 * songuyen2 / 100 * songuyen3 / 12);
        //    ViewData["KetQua1"] = ketqua.ToString("N0");
        //    ViewData["KetQua2"] = (songuyen1 + ketqua).ToString("N0");
        //    return View();
        //}


    }
}

demo-web/Controllers/MinusController.cs
using Microsoft.AspNetCore.Mvc;

namespace demo_web.Controllers
{
    public class MinusController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(int songuyen1, int songuyen2)
        {
            ViewData["SoNguyenA"] = songuyen1;
            ViewData["SoNguyenB"] = songuyen2;
            ViewData["KetQua"] = songuyen1 - songuyen2;
            return View();
        }
    }
}

demo-web/Controllers/SanPhamController.cs
// Link tới model
using demo_web.Models;
using Microsoft.AspNetCore.Mvc;
using demo_web.Models;

namespace demo_web.Controllers
{
    public class SanPhamController : Controller
    {
        //Lấy từ class SanPham bên model
        public static List<SanPham> products = new List<SanPham>();
        public IActionResult Index(bool? check = false)
        {
            if ((bool)check)
            {
                products.Clear();
            }
            else
            {
                return View(products.ToList());
            }
            return View();
        }

        [HttpPost]
        public IActionResult Index(string tensanpham, int soluong, int dongia)
        {
            var homeProducts = new SanPham(tensanpham, soluong, dongia);
            products.Add(homeProducts);
            return View(products);
        }

        public IActionResult RemoveProduct(int position)
        {
            products.RemoveAt(position - 1);
            return RedirectToAction("Index", "SanPham");
        }
    }
}

demo-web/Controllers/SumController.cs
using Microsoft.AspNetCore.Mvc;

namespace demo_web.Controllers
{
    public class SumController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(int songuyen1, int songuyen2)
        {
            ViewData["SoNguyenA"] = songuyen1;
                ViewData["SoNguyenB"] = songuyen2;
            ViewData["KetQua"] = songuyen1 + songuyen2;
            return View();
        }
    }
}

demo-web/Controllers/TinhLaiController.cs
using demo_web.Models;
using Microsoft.AspNetCore.Mvc;

namespace demo_web.Controllers
{
    public class TinhLaiController : Controller
    {
        public IActionResult Index()
        {
            //Gọi class rỗng
            LaiSuat ls = new LaiSuat();
            //Nhớ return về View
            return View(ls);
        }
        //Gọi class, nhớ HttpPost
        //Biến bên Controler phải lấy đúng name bên Index 

        [HttpPost]
        public IActionResult Index(int tiengui, int laisuatgui, int kyhan)
        {
            LaiSuat ls = new LaiSuat(tiengui, laisuatgui, kyhan); 
            return View(ls);
        }
        //{
        //    ViewData["SoNguyenA"] = songuyen1;
        //    ViewData["SoNguyenB"] = songuyen2;
        //    ViewData["SoNguyenC"] = songuyen3;
        //    double ketqua = (songuyen1 * songuyen2 / 100 * songuyen3 / 12);
        //    ViewData["KetQua1"] = ketqua.ToString("N0");
        //    ViewData["KetQua2"] = (songuyen1 + ketqua).ToString("N0");
        //    return View();
        //}

    
}}

demo-web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

demo-web/Views/LaiKep/Index.cshtml
@*Nhớ khởi tạo model theo tên gọi dẫn đến class như bên dưới*@

@model demo_web.Models.LaiKep
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<div class="d-flex flex-column">
    <h1 class="text-center my-5 text-uppercase">CÔNG CỤ TÍNH LÃI TIỀN GỬI TIẾT KIỆM</h1>
    <div class="d-flex flex-column justify-content-between gap-3">
        <form action="/LaiKep/Index" method="post">
            <div class="content-tinhlai">
                <div class="content-left col-4 mx-auto">
                    <div class="mb-3">
                        <label for="soNguyen1" class="form-label">Số tiền gửi *</label>
                        @*Tại vị trí value dùng @Model.thuộc tính bên class để lấy giá trị*@
                        <input type="number" class="form-control" id="soNguyen1" name="tiengui" value="@Model.TienGui" aria-describedby="text">

                    </div>
                    <div class="mb-3">
                        <label for="soNguyen2" class="form-label">Lãi suất gửi *</label>
                        <input type="number" class="form-control" id="soNguyen2" name="laisuatgui" value="@Model.LaiSuatGui" aria-describedby="text">
                    </div>
                    <div class="mb-3">
                        <label for="soNguyen3" class="form-label">Kỳ hạn gửi *</label>
                        <input type="number" class="form-control" id="soNguyen3" name="kyhan" value="@Model.KyHan" aria-describedby="text">
                    </div><div class="mb-3">
                        <label for="soNguyen3" class="form-label">Kỳ hạn gửi *</label>
                        <input type="number" class="form-control" id="soNguyen4" name="kyhan" value="@Model.SoLanDong" hidden aria-describedby="text">
                    </div>
                
                    <div class="input-group mb-3">
  
                           <label for="soLanDong" class="form-label">Chọn số lần đóng 1 năm: </label>
                          <select class="form-select" id="soLanDong" name="soLanDong" aria-label="Example select with button addon">
                                                    <option value="1">1</option>
                                                    <option value="2">2</option>
                                                    <option value="3">3</option>
                                                    <option value="4">4</option>
                          </select>
                    </div>

                </div>
                <div class="content-right">
                    <div class="mb-5 col-4 mx-auto">
                        <label for="ketQua1" class="form-label fw-bold">Số tiền lãi nhận được</label>
                        <input type="text" class="form-control" id="ketQua1" name="a" value="@Model.TienLai" aria-describedby="text">
                    </div>
                    <div class="mb-5 col-4 mx-auto">
                        <label for="ketQua2" class="form-label fw-bold">Tổng số tiền nhận được khi đến hạn</label>
                        <input type="text" class="form-control" id="ketQua2" name="b" value="@Model.TongTien" aria-describedby="text">
                    </div>
                </div>
            </div>

            <div class="d-flex align-items-center justify-content-center mt-5">
                <button type="submit" id="ketqua" class="btn btn-primary px-4 py-2" onclick="function()">Xem kết quả</button>
            </div>
           

        </form>
          
    </div>
</div>

 

demo-web/Views/Minus/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex flex-column">
    <h1 class="text-center my-5 text-uppercase">chương trình tính tổng hai số</h1>
    <div class="d-flex flex-column justify-content-between gap-3">
        <div class="col-4 mx-auto">
            <form action="/Minus/Index" method="post">
                <div class="mb-3">
                    <label for="soNguyen1" class="form-label">Số nguyên 1</label>
                    <input type="text" class="form-control" id="soNguyen1" name="soNguyen1" value="@ViewData["SoNguyenA"]" aria-describedby="text">
                </div>
                <div class="mb-3">
                    <label for="soNguyen2" class="form-label">Số nguyên 2</label>
                    <input type="number" class="form-control" id="soNguyen2" name="soNguyen2" value="@ViewData["SoNguyenB"]" aria-describedby="text">
                </div>
                <div class="d-flex align-items-center justify-content-center mt-5">
                    <button type="submit" id="ketqua" class="btn btn-primary px-4 py-2">Xem kết quả</button>
                </div>
            </form>
        </div>
        <div class="mb-5 col-4 mx-auto">
            <label for="ketQua" class="form-label fw-bold">Kết quả</label>
            <input type="number" class="form-control" id="ketQua" name="ketQua" value="@ViewData["KetQua"]" aria-describedby="text">
        </div>
    </div>
</div>

demo-web/Views/SanPham/Index.cshtml
@using demo_web.Models;
@*Link tới model*@
@model IEnumerable<demo_web.Models.SanPham>;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="d-flex flex-row justify-content-between gap-3">
        <div class="col-7 border-1 rounded-3 shadow-lg px-5" style="height: 680px;">
            <h2 class="fw-bold text-center pt-5 pb-4">Danh sách sản phẩm</h2>
            <hr/>
            <div style="max-height: 360px; overflow-y: auto;" class="px-3">
                <table class="table table-striped overflow-scroll">
                    <thead>
                        <tr class="text-center">
                            <th scope="col">STT</th>
                            <th scope="col">Tên sản phẩm</th>
                            <th scope="col">Số lượng</th>
                            <th scope="col">Đơn giá</th>
                            <th scope="col" class="text-end">Tạm tính</th>
                            <th scope="col">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            int i = 0;
                            foreach (var item in Model)
                            {
                                i++;
                                <tr>
                                    <td class="text-center">@i</td>
                                    <td class="text-center">@item.TenSanPham</td>
                                    <td class="text-center">@item.SoLuong</td>
                                    <td class="text-center">@item.DonGia.ToString("N0")</td>
                                    <td class="text-end">@item.TamTinh.ToString("N0")</td>
                                    <td class="text-center"><a href="@Url.Action("RemoveProduct", @*Gọi hàm RemoveProduct bên SanPham với giá trị position = i để xóa hàng ở vị trí thứ i*@ "SanPham", new { position = @i })"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a></td>
                                </tr>                                                                 @*  Cũng có nghĩa là trả về đường link /SanPham/RemoveProduct?position=i*@
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="6" class="text-center">Không có dữ liệu</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <hr />
            @if (Model != null)
            {
                double tongCong = 0;
                foreach (var item in Model)
                {
                    tongCong += item.TamTinh;
                }
                <div class="d-flex flex-column text-end">
                    <p class="fw-bold float-end px-3" id="TongThanhTien">Tổng thành tiền: @tongCong.ToString("N0") đồng</p>
                </div>
            }
            else
            {
                <div class="d-flex flex-column text-end">
                    <p class="fw-bold float-end px-3">Tổng cộng: 0 đồng</p>
                </div>
            }
        </div>
        <div class="col-5 px-5 pt-5 border rounded-3 shadow-lg">
            <h2 class="text-center fw-bold pb-4">Thông tin sản phẩm</h2>
            <hr />
            <form action="/SanPham" method="post">
                <div class="mb-4">
                    <label for="tensanpham" class="form-label fw-bolder">Tên sản phẩm</label>
                    <input type="text" class="form-control" id="tensanpham" name="tensanpham" value="" aria-describedby="text">
                </div>
                <div class="mb-4">
                    <label for="soluong" class="form-label fw-bolder">Số lượng</label>
                    <input type="number" class="form-control" id="soluong" name="soluong" value="" aria-describedby="text">
                </div>
                <div class="mb-5">
                    <label for="dongia" class="form-label fw-bolder">Đơn giá bán</label>
                    <input type="number" class="form-control" id="dongia" name="dongia" value="" aria-describedby="text">
                </div>
                <hr />
                <div class="d-flex align-items-center justify-content-center my-5 gap-5">
                    <button type="submit" id="themgiohang" class="btn btn-primary px-4 py-2">Thêm vào giỏ hàng</button>
                    <a type="button" id="thanhtoan" class="btn btn-outline-warning px-4 py-2" href="@Url.Action("Index",@*Gọi hàm Index bên SanPham với giá trị check = true để clear list*@"SanPham", new { check = true})" onclick="HienThiThongBao()">Thanh toán</a>
                                                                                                                                    @*Trả về link /SanPham/Index?check=true*@
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function HienThiThongBao(){
        var message = $('#TongThanhTien').text()
        alert(message)
    }
</script>

demo-web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demo_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/demo_web.styles.css" asp-append-version="true" />
    <link href="~/font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    <link href="~/font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">demo_web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Sum" asp-action="Index">Tinh Tong</a>
                        </li>
                         <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Minus" asp-action="Index">Tinh Hieu</a>
                        </li>
                         <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="TinhLai" asp-action="Index">TÍNH LÃI TIỀN GỬI</a>
                        </li> <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="LaiKep" asp-action="Index">TÍNH LÃI KEP</a>
                        </li></li> <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="SanPham" asp-action="Index">DANH SÁCH SẢN PHẨM</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - demo_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

demo-web/Views/Sum/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex flex-column">
    <h1 class="text-center my-5 text-uppercase">chương trình tính tổng hai số</h1>
    <div class="d-flex flex-column justify-content-between gap-3">
        <div class="col-4 mx-auto">
            <form action="/Sum/Index" method="post">
                <div class="mb-3">
                    <label for="soNguyen1" class="form-label">Số nguyên 1</label>
                    <input type="text" class="form-control" id="soNguyen1" name="soNguyen1" value="@ViewData["SoNguyenA"]" aria-describedby="text">
                </div>
                <div class="mb-3">
                    <label for="soNguyen2" class="form-label">Số nguyên 2</label>
                    <input type="number" class="form-control" id="soNguyen2" name="soNguyen2" value="@ViewData["SoNguyenB"]" aria-describedby="text">
                </div>
                <div class="d-flex align-items-center justify-content-center mt-5">
                    <button type="submit" id="ketqua" class="btn btn-primary px-4 py-2">Xem kết quả</button>
                </div>
            </form>
        </div>
        <div class="mb-5 col-4 mx-auto">
            <label for="ketQua" class="form-label fw-bold">Kết quả</label>
            <input type="number" class="form-control" id="ketQua" name="ketQua" value="@ViewData["KetQua"]" aria-describedby="text">
        </div>
    </div>
</div>

demo-web/Views/TinhLai/Index.cshtml
@*Nhớ khởi tạo model theo tên gọi dẫn đến class như bên dưới*@

@model demo_web.Models.LaiSuat
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<div class="d-flex flex-column">
    <h1 class="text-center my-5 text-uppercase">CÔNG CỤ TÍNH LÃI TIỀN GỬI TIẾT KIỆM</h1>
    <div class="d-flex flex-column justify-content-between gap-3">
            <form action="/TinhLai/Index" method="post">
        <div class="content-tinhlai">
            <div class="content-left col-4 mx-auto">
                <div class="mb-3">
                    <label for="soNguyen1" class="form-label">Số tiền gửi *</label>
                    @*Tại vị trí value dùng @Model.thuộc tính bên class để lấy giá trị*@
                    <input type="number" class="form-control" id="soNguyen1" name="tiengui" value="@Model.TienGui" aria-describedby="text">
                    
                </div>
                <div class="mb-3">
                    <label for="soNguyen2" class="form-label">Lãi suất gửi *</label>
                    <input type="number" class="form-control" id="soNguyen2" name="laisuatgui" value="@Model.LaiSuatGui" aria-describedby="text">
                </div>
                <div class="mb-3">
                    <label for="soNguyen3" class="form-label">Kỳ hạn gửi *</label>
                    <input type="number" class="form-control" id="soNguyen3" name="kyhan" value="@Model.KyHan" aria-describedby="text">
                </div>
                 
            
             </div>
            <div class ="content-right">
                <div class="mb-5 col-4 mx-auto">
                    <label for="ketQua1" class="form-label fw-bold">Số tiền lãi nhận được</label>
                    <input type="text" class="form-control" id="ketQua1" name="a" value="@Model.TienLai" aria-describedby="text">
                </div>
                <div class="mb-5 col-4 mx-auto">
                    <label for="ketQua2" class="form-label fw-bold">Tổng số tiền nhận được khi đến hạn</label>
                    <input type="text" class="form-control" id="ketQua2" name="b" value="@Model.TongTien" aria-describedby="text">
                </div>
            </div>
        </div>
        
       <div class="d-flex align-items-center justify-content-center mt-5">
                    <button type="submit" id="ketqua" class="btn btn-primary px-4 py-2">Xem kết quả</button>
                </div>
        </form>
    </div>
</div>